### ISSUE TITLE
Timestamp Problem - Server out of sync

### ISSUE THREAD

**Issue by usama33** [jaggedsoft/node-binance-api#69]
I am getting issue due to server timestamp that gets out of sync. When I try to get balances. It throws following error;

`node_modules/node-binance-api/node-binance-api.js:268`
`if ( typeof data.balances === 'undefined' ) {`
`TypeError: Cannot read property 'balances' of undefined`

Upon investigating further and printing out the error that we are receiving from the server. We found following error message;

`body: '{"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server\'s time."}'`

I manually tried to change timestamp in the data.timestamp (line # 83) by 4 seconds behind and it worked. We faced this problem a week ago as well where we changed time by -1. Any idea why this could be the problem?

**Comment by jaggedsoft** [comment]
Someone else just filed a similar issue
https://github.com/jaggedsoft/node-binance-api/issues/68

Please tell me if the problem persists
If it does, a solution that I can think of is to synchronize with the servers time when the program is first started

**Comment by usama33** [comment]
Yes, the problem still exists.. I tried different ranges for recWindown but it didn't work.

**Comment by jaggedsoft** [comment]
I am working on a `useServerTime` option so that we will synchronize with the server time. I will post the update once it's tested

**Comment by usama33** [comment]
Sweet!

**Comment by jaggedsoft** [comment]
Resolved in `v0.4.5`

See: https://github.com/jaggedsoft/node-binance-api/blob/master/examples/fix-timestamp-error.js

**Comment by alvarheras** [comment]
Hey, looks like the mistake persists, any ideas?

I tried to synchronize with this module

[timesync](https://www.npmjs.com/package/timesync)

But without success, I have the latest version of the project

**Comment by jaggedsoft** [comment]
What mistake? Binance will reject timestamps that are out of range. The easiest solution is to sync your server time (with linux use NTP) or run this program with the useServerTime option provided

```
const binance = require('node-binance-api');
binance.options({
  APIKEY: '<key>',
  APISECRET: '<secret>',
  useServerTime: true
});
```

**Comment by alvarheras** [comment]
Hi, this error

`  body: '{"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server\'s time."}' }`

My code 
```

const binance = require('node-binance-api');
binance.options({
  APIKEY: '',
  APISECRET: '',
  useServerTime: true // If you get timestamp errors, synchronize to server time at startup
});
// FUNCTIONS
function main(){
	binance.trades("ICNBTC", (error, trades, symbol) => {
	  console.log(symbol+" trade history ** ", trades);
	  console.log(error);
	});
}
main();
```

In my case even using this option the error persists

**Comment by jaggedsoft** [comment]
@alvarheras try doing it this way instead

```js
const binance = require('node-binance-api');
binance.options({
  APIKEY: '',
  APISECRET: ''
});
binance.useServerTime(function() {
	binance.trades("ICNBTC", (error, trades, symbol) => {
	  if ( error ) return console.error(error);
	  console.log(symbol+" trade history ** ", trades);
	});
});
```

**Comment by jaggedsoft** [comment]
The difference here is we are waiting for the synchronization to finish before we run any other code

**Comment by ShayGaming24** [comment]
Worked for me too, in 2021 :D thanks a lot for the solution
